import { useEffect, useRef, useState } from "react";
import QrScanner from "qr-scanner";
import {
  QrCode, CheckCircle2, AlertTriangle, FileWarning, ScanLine, PenLine,
  Camera, CameraOff, RefreshCw, Zap, ZapOff, ExternalLink, Loader2, Globe,
} from "lucide-react";
import { api } from "../api";
import Spinner from "./Spinner";

// Demo QR codes wired to specific scenarios in backend/app/seed.py. These are
// still useful even with a real camera: (a) as a fallback when no camera is
// available/permitted, and (b) to jump straight to a specific judgement
// scenario without needing to print/display a QR code. Real, scannable PNGs
// for these same codes are generated by scripts/generate-demo-qr.mjs into
// public/demo-qr/ and can be viewed at /demo-qr.html for actual camera testing.
// qr-scanner's start() collapses EVERY getUserMedia failure (NotAllowedError,
// NotFoundError, NotReadableError, OverconstrainedError, …) into a single bare
// string throw of "Camera not found." - it tries several camera constraints in
// a loop with an empty `catch {}` and discards the real DOMException. So the
// thrown error tells us nothing about *why* it failed. Ask the Permissions API
// instead to tell "permission blocked" apart from "no usable camera".
// Returns "granted" | "denied" | "prompt" | null (null = can't determine;
// Firefox and older Safari don't support the "camera" permission name).
async function getCameraPermissionState() {
  try {
    if (!navigator.permissions?.query) return null;
    const status = await navigator.permissions.query({ name: "camera" });
    return status.state;
  } catch {
    return null;
  }
}

const DEMO_CODES = [
  { code: "QR-A1001", label: "QR-A1001", desc: "成功讀取・符合規定・會觸發重複警示", accent: "success", icon: CheckCircle2 },
  { code: "QR-A1002", label: "QR-A1002", desc: "成功讀取・開單逾時", accent: "warning", icon: AlertTriangle },
  { code: "QR-A1003", label: "QR-A1003", desc: "成功讀取・資料異常（開單時間早於停車時間）", accent: "danger", icon: FileWarning },
  { code: "QR-A1004", label: "QR-A1004", desc: "成功讀取・符合規定・無重複", accent: "success", icon: CheckCircle2 },
  { code: "QR-A1005", label: "QR-A1005", desc: "QR 解碼成功但查詢頁讀取失敗", accent: "warning", icon: AlertTriangle },
  { code: "QR-BAD-SCAN", label: "QR-BAD-SCAN", desc: "模擬掃描失敗（無法辨識的 QR）", accent: "neutral", icon: FileWarning },
];

// Camera lifecycle phases:
//   checking    - feature-detecting secure context / camera presence
//   unsupported - no camera API, no camera device, or not a secure context
//   idle        - ready, waiting for the inspector to tap "開始相機掃描"
//   starting    - start() called, waiting for camera permission/stream
//   active      - live video feed running, watching for a decode
//   denied      - user denied camera permission
//   error       - camera failed to start for some other reason
function CameraScanner({ onDecoded, disabled }) {
  const videoRef = useRef(null);
  const scannerRef = useRef(null);
  const processingRef = useRef(false);
  const [phase, setPhase] = useState("checking");
  const [errorMessage, setErrorMessage] = useState("");
  const [facingMode, setFacingMode] = useState("environment");
  const [multipleCameras, setMultipleCameras] = useState(false);
  const [hasFlash, setHasFlash] = useState(false);
  const [flashOn, setFlashOn] = useState(false);

  // Feature-detect once on mount. getUserMedia requires a secure context
  // (HTTPS, or http://localhost) - this will correctly report "unsupported"
  // if the admin/inspector app is ever served over plain http on a LAN IP,
  // which is an easy trap when field-testing the Docker build on a phone.
  useEffect(() => {
    let cancelled = false;
    (async () => {
      if (!window.isSecureContext || !navigator.mediaDevices?.getUserMedia) {
        if (!cancelled) {
          setPhase("unsupported");
          setErrorMessage(
            !window.isSecureContext
              ? "此頁面不是安全連線（HTTPS），瀏覽器會封鎖相機權限，請改用 HTTPS 存取或使用下方示範模式。"
              : "此瀏覽器不支援相機掃描，請改用下方示範模式。"
          );
        }
        return;
      }
      const hasCamera = await QrScanner.hasCamera().catch(() => false);
      if (!cancelled) {
        if (!hasCamera) {
          setPhase("unsupported");
          setErrorMessage("找不到可用的相機裝置，請改用下方示範模式。");
        } else {
          setPhase("idle");
        }
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  // Always tear down the camera stream + worker when leaving this screen.
  useEffect(() => {
    return () => {
      scannerRef.current?.destroy();
      scannerRef.current = null;
    };
  }, []);

  async function handleDecode(result) {
    if (processingRef.current) return;
    processingRef.current = true;
    scannerRef.current?.stop();
    await onDecoded(result.data);
    processingRef.current = false;
  }

  async function startCamera() {
    setPhase("starting");
    setErrorMessage("");
    try {
      if (!scannerRef.current) {
        scannerRef.current = new QrScanner(videoRef.current, handleDecode, {
          onDecodeError: () => {}, // fires per-frame while no code is visible; not a real error
          preferredCamera: facingMode,
          maxScansPerSecond: 10,
          highlightScanRegion: true,
          highlightCodeOutline: true,
          returnDetailedScanResult: true,
        });
      }
      await scannerRef.current.start();
      setPhase("active");

      QrScanner.listCameras()
        .then((cams) => setMultipleCameras(cams.length > 1))
        .catch(() => setMultipleCameras(false));
      scannerRef.current
        .hasFlash()
        .then(setHasFlash)
        .catch(() => setHasFlash(false));
    } catch (err) {
      // qr-scanner throws a bare "Camera not found." string for ALL failures
      // (see getCameraPermissionState), so err.name is unreliable. Use the
      // Permissions API to give the inspector an accurate next step.
      const permission = await getCameraPermissionState();
      const raw = String(err?.message || err || "");
      if (
        err?.name === "NotAllowedError" ||
        permission === "denied" ||
        /permission|denied|not\s*allowed/i.test(raw)
      ) {
        setPhase("denied");
        setErrorMessage(
          "無法取得相機權限。若瀏覽器沒有跳出授權提示，通常是先前已封鎖本頁的相機權限：請點擊網址列的相機/鎖頭圖示改為「允許」後重試，或改用下方示範模式。"
        );
      } else {
        // Permission is granted or未定，但仍拿不到影像：多半是沒有可用相機、
        // 相機被其他程式占用，或在不支援相機的內嵌瀏覽器（如 LINE / FB 內開啟）。
        setPhase("error");
        setErrorMessage(
          "無法啟動相機。請確認裝置有可用的相機、沒有其他程式正在使用它，並改用系統瀏覽器（Safari / Chrome）而非 App 內建瀏覽器，或改用下方示範模式。"
        );
      }
    }
  }

  function stopCamera() {
    scannerRef.current?.stop();
    setPhase("idle");
  }

  async function switchCamera() {
    const next = facingMode === "environment" ? "user" : "environment";
    setFacingMode(next);
    try {
      await scannerRef.current?.setCamera(next);
    } catch {
      // best effort - not every device honors the preference
    }
  }

  async function toggleFlash() {
    try {
      await scannerRef.current?.toggleFlash();
      setFlashOn(scannerRef.current?.isFlashOn() ?? false);
    } catch {
      // flash not supported on this device/browser - ignore
    }
  }

  if (phase === "checking") {
    return <Spinner label="檢查相機狀態…" />;
  }

  if (phase === "unsupported") {
    return (
      <div className="info-box info">
        <CameraOff size={16} />
        <span>{errorMessage}</span>
      </div>
    );
  }

  return (
    <div className="qr-camera">
      <div className={`qr-video-wrap ${phase !== "active" ? "is-inactive" : ""}`}>
        {/* Kept mounted (not conditionally rendered) so the QrScanner instance
            always has a stable <video> element to attach to. */}
        <video ref={videoRef} muted playsInline />
        {phase !== "active" && (
          <div className="qr-video-placeholder">
            <QrCode size={28} />
          </div>
        )}
      </div>

      {(phase === "denied" || phase === "error") && (
        <div className="error-box">
          <AlertTriangle size={16} />
          <span>{errorMessage}</span>
        </div>
      )}

      <div className="qr-camera-controls">
        {phase === "idle" && (
          <button className="btn-primary btn-block" disabled={disabled} onClick={startCamera}>
            <Camera size={15} /> 開始相機掃描
          </button>
        )}
        {phase === "starting" && (
          <button className="btn-primary btn-block" disabled>
            <Loader2 size={15} className="spin-icon" /> 開啟相機中…
          </button>
        )}
        {phase === "active" && (
          <div className="qr-camera-active-row">
            <button className="btn-secondary" onClick={stopCamera}>
              <CameraOff size={15} /> 停止
            </button>
            {multipleCameras && (
              <button className="btn-secondary" onClick={switchCamera}>
                <RefreshCw size={15} /> 切換鏡頭
              </button>
            )}
            {hasFlash && (
              <button className="btn-secondary" onClick={toggleFlash}>
                {flashOn ? <ZapOff size={15} /> : <Zap size={15} />} 手電筒
              </button>
            )}
          </div>
        )}
        {(phase === "denied" || phase === "error") && (
          <button className="btn-secondary btn-block" onClick={startCamera}>
            <RefreshCw size={15} /> 重試
          </button>
        )}
      </div>
      {phase === "active" && (
        <p className="muted small qr-camera-hint">將停車單上的 QR Code 對準框內，會自動辨識。</p>
      )}
    </div>
  );
}

export default function QRScan({ onResult, onManualFallback }) {
  const [scanning, setScanning] = useState(false);

  async function doScan(code) {
    setScanning(true);
    try {
      const res = await api.scanQr(code);
      if (res.status === "success") {
        onResult({ status: "success", dataSource: "AUTO_QR", ticket: res.ticket, webInfo: res.web_info || null });
      } else if (res.status === "fetch_failed") {
        onResult({
          status: "fetch_failed",
          dataSource: "MANUAL_FROM_QR_PAGE",
          query_url: res.query_url,
          page_preview: res.page_preview,
        });
      } else {
        onResult({ status: "scan_failed", dataSource: "MANUAL_FROM_TICKET" });
      }
    } finally {
      setScanning(false);
    }
  }

  return (
    <div className="card">
      <div className="card-icon-heading">
        <span className="icon-badge">
          <QrCode size={18} />
        </span>
        <h2>掃描停車單 QR Code</h2>
      </div>

      <CameraScanner onDecoded={doScan} disabled={scanning} />
      {scanning && <Spinner label="辨識中…" />}

      <div className="divider" />
      <p className="muted small">
        沒有相機、相機被拒絕，或想直接測試特定情境？可使用下列示範 QR Code：
      </p>
      <div className="qr-grid">
        {DEMO_CODES.map((d) => {
          const Icon = d.icon;
          return (
            <button
              key={d.code}
              className={`qr-tile accent-${d.accent}`}
              disabled={scanning}
              onClick={() => doScan(d.code)}
            >
              <span className="qr-tile-title">
                <Icon size={14} />
                {d.label}
              </span>
              <span className="qr-tile-desc">{d.desc}</span>
            </button>
          );
        })}
      </div>
      <p className="muted small">
        想用手機相機實際測試？在另一台裝置開啟{" "}
        <a href="/demo-qr.html" target="_blank" rel="noopener noreferrer">
          示範 QR Code 頁面 <ExternalLink size={12} />
        </a>{" "}
        顯示上述代碼的真實 QR 圖片，再用本頁相機掃描。
      </p>
      <TicketUrlInput onScan={doScan} scanning={scanning} />
      <ManualCodeInput onScan={doScan} scanning={scanning} />
      <div className="divider" />
      <button className="btn-link" onClick={onManualFallback}>
        <PenLine size={14} /> 直接人工輸入帳單資料
      </button>
    </div>
  );
}

// Online query: paste (or let the camera decode) a real 臺北市停車繳費通知單 QR
// URL; the backend headless worker fetches the query site and auto-fills the
// ticket fields. This is the same path a real camera scan takes.
function TicketUrlInput({ onScan, scanning }) {
  const [url, setUrl] = useState("");
  const looksLikeUrl = /^https?:\/\//i.test(url.trim());
  return (
    <div className="info-box" style={{ display: "block" }}>
      <p className="small" style={{ margin: "0 0 6px", display: "flex", alignItems: "center", gap: 6 }}>
        <Globe size={14} /> <strong>線上查詢</strong>：貼上停車單 QR 網址，自動查詢並帶入資料
      </p>
      <label style={{ margin: 0 }}>
        <input
          value={url}
          onChange={(e) => setUrl(e.target.value)}
          placeholder="https://parkingfee.pma.gov.taipei/qr?tno=…"
          inputMode="url"
        />
      </label>
      <button
        className="btn-secondary btn-block"
        style={{ marginTop: 8 }}
        disabled={scanning || !looksLikeUrl}
        onClick={() => onScan(url.trim())}
      >
        <Globe size={15} /> 線上查詢帶入
      </button>
    </div>
  );
}

function ManualCodeInput({ onScan, scanning }) {
  const [customCode, setCustomCode] = useState("");
  return (
    <>
      <label>
        或輸入任意 QR 內容測試「掃描失敗」情境
        <input value={customCode} onChange={(e) => setCustomCode(e.target.value)} placeholder="例如 UNKNOWN-CODE" />
      </label>
      <button className="btn-secondary btn-block" disabled={scanning || !customCode} onClick={() => onScan(customCode)}>
        <ScanLine size={15} /> 掃描
      </button>
    </>
  );
}
